### PR TITLE
Migrated to using go mod to manage dependencies

### PR DESCRIPTION
**Pull request by huydoan2**
This PR attempts to use `go mod`, a new technique, to manage dependencies.

We will address cleaning up gradle build code in a separate PR.

### CODE REVIEW

**Comment by rabbah** [comment]
Should we even keep gradle build rather than use the go build?

**Comment by rabbah** [comment]
Thanks for your contributions @huydoan2.

**Comment by huydoan2** [comment]
> Should we even keep gradle build rather than use the go build?

I think it's simpler to keep one build system around. We could add a Makefile for convenience.

**Comment by mrutkows** [comment]
@rabbah would love to remove Gradle... perhaps a follow-on PR...

**Pull request merged**
