### PR TITLE
Fix travis build

### PR DESCRIPTION
**Pull request by chetanmeh**
`setuptools` install was failing due to package update error in `pip install step`

```
$ pip install --upgrade pip setuptools

/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.

  warnings.warn(warning, RequestsDependencyWarning)

DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support

Collecting pip

  Downloading https://files.pythonhosted.org/packages/30/db/9e38760b32e3e7f40cce46dd5fb107b8c73840df38f0046d8e6514e675a1/pip-19.2.3-py2.py3-none-any.whl (1.4MB)

Collecting setuptools

  Downloading https://files.pythonhosted.org/packages/6a/9a/50fadfd53ec909e4399b67c74cc7f4e883488035cfcdb90b685758fa8b34/setuptools-41.4.0-py2.py3-none-any.whl (580kB)

Installing collected packages: pip, setuptools

  Found existing installation: pip 19.2.1

    Uninstalling pip-19.2.1:

ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/bin/pip'
Consider using the `--user` option or check the permissions.
WARNING: You are using pip version 19.2.1, however version 19.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The command "pip install --upgrade pip setuptools" failed and exited with 1 during 
```

Similar to apache/openwhisk#4683 fix here was to to `--user` option with pip command

### CODE REVIEW

**Comment by chetanmeh** [comment]
Looks like we cannot force use of `openjdk8` as the primary language in tarvis is `go` and Travis does not support specifying multiple languages (travis-ci/travis-ci#4090). So

1. Get build going with JDK 11
2. OR Figure out installing JDK 8

**Comment by rabbah** [comment]
These are the tests that failed:
```
org.apache.openwhisk.core.cli.test.WskCliWebActionsTests > Wsk Web Actions should ensure __ow_headers contains the proper content-type FAILED
org.apache.openwhisk.core.cli.test.WskCliWebActionsTests > Wsk Web Actions should create a web action accessible via HTTPS FAILED
org.apache.openwhisk.core.cli.test.WskCliWebActionsTests > Wsk Web Actions should create a web action requiring authentication accessible via HTTPS FAILED
org.apache.openwhisk.core.cli.test.WskCliWebActionsTests > Wsk Web Actions should ensure that CORS header is preserved for custom options FAILED
org.apache.openwhisk.core.cli.test.WskCliWebActionsTests > Wsk Web Actions should ensure that default CORS header is preserved FAILED
org.apache.openwhisk.core.cli.test.WskCliWebActionsTests > Wsk Web Actions should invoke web action to ensure the returned body argument is correct FAILED
org.apache.openwhisk.core.cli.test.WskCliWebActionsTests > Wsk Web Actions should reject invocation of web action with invalid accept header FAILED
org.apache.openwhisk.core.cli.test.WskCliWebActionsTests > Wsk Web Actions should support multiple response header values FAILED
org.apache.openwhisk.core.cli.test.WskCliWebActionsTests > Wsk Web Actions should handle http web action returning JSON as string FAILED
org.apache.openwhisk.core.cli.test.WskCliWebActionsTests > Wsk Web Actions should handle http web action with base64 encoded binary response FAILED
org.apache.openwhisk.core.cli.test.WskCliWebActionsTests > Wsk Web Actions should create a web action making a HEAD request FAILED
system.basic.WskCliSequenceTests > Wsk Sequence should replace atomic component in a sequence that is too long and report invoke error FAILED
```

they share this error in common: 
```
web action requiring authentication accessible via HTTPS FAILED
    java.io.FileNotFoundException: keystore (No such file or directory)
```

**Comment by dgrove-oss** [comment]
There was a change in .travis.yml that seemed like perhaps a typo?

https://github.com/apache/openwhisk-cli/pull/458/files#diff-354f30a63fb0907d4ad57269548329e3R31

I took out that line in #460; lets see if that does anything wrt the keystore

**Comment by dgrove-oss** [comment]
I got a clean run on #460.  I squashed to a single commit with a Co-Authored tag.  Assuming I didn't fat finger the squash we should be back in business.

**Comment by rabbah** [comment]
Approved 460 but will wait for travis this time before merging but feel free too also. Going to close this PR then.

**Pull request closed without merging**
